import 'control_action.dart';
import 'control_profile.dart';

class ControlProfileRegistry {
  const ControlProfileRegistry._();

  static const Map<String, ControlProfile> profiles = {
    'youtube': ControlProfile(
      appId: 'youtube',
      displayName: 'YouTube',
      packageNames: ['com.google.android.youtube.tv', 'com.google.android.youtube'],
      supportedActions: {
        ControlAction.openApp,
        ControlAction.search,
        ControlAction.play,
        ControlAction.pause,
        ControlAction.resume,
        ControlAction.next,
        ControlAction.back,
        ControlAction.up,
        ControlAction.down,
        ControlAction.left,
        ControlAction.right,
        ControlAction.select,
        ControlAction.home,
        ControlAction.menu,
        ControlAction.volumeUp,
        ControlAction.volumeDown,
        ControlAction.mute,
      },
      primaryStrategy: 'android_package_launch',
      fallbackStrategy: 'android_media_key_event',
    ),
    'vlc': ControlProfile(
      appId: 'vlc',
      displayName: 'VLC',
      packageNames: ['org.videolan.vlc'],
      supportedActions: {
        ControlAction.openApp,
        ControlAction.search,
        ControlAction.play,
        ControlAction.pause,
        ControlAction.resume,
        ControlAction.next,
        ControlAction.previous,
        ControlAction.fastForward,
        ControlAction.rewind,
        ControlAction.back,
        ControlAction.up,
        ControlAction.down,
        ControlAction.left,
        ControlAction.right,
        ControlAction.select,
        ControlAction.home,
        ControlAction.menu,
        ControlAction.volumeUp,
        ControlAction.volumeDown,
        ControlAction.mute,
      },
      primaryStrategy: 'android_package_launch',
      fallbackStrategy: 'android_media_key_event',
    ),
    'spotify': ControlProfile(
      appId: 'spotify',
      displayName: 'Spotify',
      packageNames: ['com.spotify.tv.android', 'com.spotify.music'],
      supportedActions: {
        ControlAction.openApp,
        ControlAction.search,
        ControlAction.play,
        ControlAction.pause,
        ControlAction.resume,
        ControlAction.next,
        ControlAction.previous,
        ControlAction.back,
        ControlAction.up,
        ControlAction.down,
        ControlAction.left,
        ControlAction.right,
        ControlAction.select,
        ControlAction.home,
        ControlAction.menu,
        ControlAction.volumeUp,
        ControlAction.volumeDown,
        ControlAction.mute,
      },
      primaryStrategy: 'android_package_launch',
      fallbackStrategy: 'android_media_key_event',
    ),
    'settings': ControlProfile(
      appId: 'settings',
      displayName: 'Settings',
      packageNames: [],
      supportedActions: {
        ControlAction.openApp,
        ControlAction.up,
        ControlAction.down,
        ControlAction.left,
        ControlAction.right,
        ControlAction.select,
        ControlAction.back,
        ControlAction.home,
        ControlAction.menu,
        ControlAction.volumeUp,
        ControlAction.volumeDown,
        ControlAction.mute,
      },
      primaryStrategy: 'android_system_settings_intent',
      fallbackStrategy: 'none',
    ),
    'cast': ControlProfile(
      appId: 'cast',
      displayName: 'Screen Cast',
      packageNames: [],
      supportedActions: {
        ControlAction.openApp,
        ControlAction.up,
        ControlAction.down,
        ControlAction.left,
        ControlAction.right,
        ControlAction.select,
        ControlAction.back,
        ControlAction.home,
        ControlAction.menu,
      },
      primaryStrategy: 'android_cast_settings_intent',
      fallbackStrategy: 'android_system_settings_intent',
    ),
    'local_files': ControlProfile(
      appId: 'local_files',
      displayName: 'Local Files',
      packageNames: ['org.videolan.vlc'],
      supportedActions: {
        ControlAction.openApp,
        ControlAction.play,
        ControlAction.pause,
        ControlAction.resume,
        ControlAction.next,
        ControlAction.previous,
        ControlAction.back,
        ControlAction.up,
        ControlAction.down,
        ControlAction.left,
        ControlAction.right,
        ControlAction.select,
        ControlAction.home,
        ControlAction.menu,
        ControlAction.volumeUp,
        ControlAction.volumeDown,
        ControlAction.mute,
      },
      primaryStrategy: 'android_document_picker',
      fallbackStrategy: 'android_package_launch',
    ),
    'media': ControlProfile(
      appId: 'media',
      displayName: 'Media Session',
      packageNames: [],
      supportedActions: {
        ControlAction.play,
        ControlAction.pause,
        ControlAction.resume,
        ControlAction.next,
        ControlAction.previous,
        ControlAction.fastForward,
        ControlAction.rewind,
      },
      primaryStrategy: 'android_media_session_transport',
      fallbackStrategy: 'android_media_key_event',
    ),
    'system': ControlProfile(
      appId: 'system',
      displayName: 'System Navigation',
      packageNames: [],
      supportedActions: {
        ControlAction.back,
        ControlAction.up,
        ControlAction.down,
        ControlAction.left,
        ControlAction.right,
        ControlAction.select,
        ControlAction.home,
        ControlAction.menu,
        ControlAction.volumeUp,
        ControlAction.volumeDown,
        ControlAction.mute,
      },
      primaryStrategy: 'android_back_dispatcher',
      fallbackStrategy: 'none',
    ),
  };

  static ControlProfile? profileFor(String appId) => profiles[appId];
}
