[versions]
agp = "8.11.1"
kotlin = "2.2.20"
coreKtx = "1.16.0"
appcompat = "1.7.1"
material = "1.12.0"
junit4 = "4.13.2"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
google-material = { group = "com.google.android.material", name = "material", version.ref = "material" }
junit4 = { group = "junit", name = "junit", version.ref = "junit4" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

